//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCapaPersonas.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MantenimientoPersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MantenimientoPersona(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MantenimientoPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MantenimientoPersonaAsync(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListaPersonas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetListaPersonas(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListaPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetListaPersonasAsync(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebAppCapaPersonas.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebAppCapaPersonas.ServiceReference.WebServiceSoap>, WebAppCapaPersonas.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MantenimientoPersona(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion) {
            return base.Channel.MantenimientoPersona(pNif, pNombre_Completo, pDireccion, pTelefono, pPoblacion, pProvincia, pCodigo_Postal, pNum_Seguridad_Social, pAccion);
        }
        
        public System.Threading.Tasks.Task<string> MantenimientoPersonaAsync(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion) {
            return base.Channel.MantenimientoPersonaAsync(pNif, pNombre_Completo, pDireccion, pTelefono, pPoblacion, pProvincia, pCodigo_Postal, pNum_Seguridad_Social, pAccion);
        }
        
        public System.Data.DataSet GetListaPersonas(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion) {
            return base.Channel.GetListaPersonas(pNif, pNombre_Completo, pDireccion, pTelefono, pPoblacion, pProvincia, pCodigo_Postal, pNum_Seguridad_Social, pAccion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetListaPersonasAsync(string pNif, string pNombre_Completo, string pDireccion, string pTelefono, string pPoblacion, string pProvincia, string pCodigo_Postal, string pNum_Seguridad_Social, string pAccion) {
            return base.Channel.GetListaPersonasAsync(pNif, pNombre_Completo, pDireccion, pTelefono, pPoblacion, pProvincia, pCodigo_Postal, pNum_Seguridad_Social, pAccion);
        }
    }
}
